// Generated by Sonnet 3.5.0
import { AbstractControl, ValidationErrors } from '@angular/forms';

export function creditCardValidator(control: AbstractControl): ValidationErrors | null {
  if (!control.value) {
    return null;
  }

  const value = control.value.replace(/\s/g, '');

  // Luhn algorithm for card validation
  let sum = 0;
  let isEven = false;

  for (let i = value.length - 1; i >= 0; i--) {
    let digit = parseInt(value[i]);

    if (isEven) {
      digit *= 2;
      if (digit > 9) {
        digit -= 9;
      }
    }

    sum += digit;
    isEven = !isEven;
  }

  return (sum % 10 === 0) ? null : { creditCard: true };
}

export function expiryDateValidator(control: AbstractControl): ValidationErrors | null {
  if (!control.value) {
    return null;
  }

  const [month, year] = control.value.split('/');
  const expiry = new Date(2000 + parseInt(year), parseInt(month) - 1);
  const today = new Date();

  return expiry > today ? null : { expiryDate: true };
}
